version: "3.9"  # Docker Compose 文件版本

services:  # 定义服务列表
  dy-api:  # 服务名称
    image: dy-api:latest  # 使用的 Docker 镜像
    container_name: dy-api  # 容器名称
    restart: always  # 容器退出后总是重启
    volumes: # 挂载卷配置
      - ./data/douyin_web/config.yaml:/app/crawlers/douyin/web/config.yaml
      - ./data/tiktok_web/config.yaml:/app/crawlers/tiktok/web/config.yaml
      - ./data/tiktok_app/config.yaml:/app/crawlers/tiktok/app/config.yaml
    environment:  # 环境变量配置
      TZ: Asia/Shanghai  # 设置时区为亚洲/上海
      PUID: 1026  # 设置容器内部的用户 ID
      PGID: 100  # 设置容器内部的用户组 ID
    ports:
      - 8001:80
    privileged: true  # 设置特权模式以便容器内部可以执行特权操作